language: node_js

node_js:
   - "node" # Latest node version
   - "lts/*" # Latest LTS version
   - "10"
   - "8"
   - "8.10"

jobs:
   include:
      stage: test
      before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm@6.4.1; fi
      script:
         - node --version
         - npm --version
         - grunt standards
         - npm test
      # For code coverage:
      after_success:
         cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

   include:
      stage: deploy
      node_js: "8.10"
      script:
         - grunt build
      before_deploy:
         - curl https://raw.githubusercontent.com/createdbyfireside/authorized-publishers/master/keys/trusted-keys.txt > trusted-keys.txt
         - curl https://raw.githubusercontent.com/createdbyfireside/authorized-publishers/master/keys/authorized-publishers.asc > authorized-publishers.asc
         - echo "Importing authorized publisher's gpg keys"
         # Import gpg keys that are authorized to trigger npm publish
         - gpg --import authorized-publishers.asc
         - echo "Importing gpg trust store"
         # Import trust store
         - gpg --import-ownertrust < trusted-keys.txt
         - echo "Verifying tag $TRAVIS_TAG"
         # Verify the current tag with git
         - git tag -v $TRAVIS_TAG
      deploy:
         provider: npm
         email: $NPM_AUTH_EMAIL
         api_key: $NPM_AUTH_TOKEN
         skip_cleanup: true
         on:
            tags: true
            condition: $TRAVIS_TAG =~ ^v[0-9].*$
